language: node_js
node_js:
  - "stable"
cache:
  directories:
    - node_modules
install:
  - yarn install
script:
  - yarn test
  - yarn run build

deploy:
  provider: netlify
  dir: "_build/"

on:
  branch: master